collector:
  influential_accounts:
    - "karpathy"
    - "OpenAI"
    - "AndrewYNg"
    - "geoffreyhinton"
    - "drfeifei"
    - "lexfridman"
    - "ycombinator"
    - "GoogleDeepMind"
    - "jovialjoy"
    - "sama"
    - "AnthropicAI"
    - "AiBreakfast"
    - "ilyasut"
    - "NeelNanda5"
    - "huggingface"
    - "jxmnop"
    - "rryssf_"
    - "TechCrunch"
    - "Kimi_Moonshot"
    - "NousResearch"
    - "alex_prompter"
    - "rohanpaul_ai"
    - "JeffDean"
    - "ylecun"
    - "_avichawla"
    - "steipete"
    - "andonlabs"
    - "EpochAIResearch"
    - "bcherny"
    - "tszzl"
    - "polynoamial"
    - "naval"
    - "demishassabis"
    - "EMostaque"
    - "raizamrtn"
    - "thinkymachines"
    - "marmaduke091"
  account_fetch_limit: 100

blog_sources:
  - "https://newsletter.ruder.io/"
  - "https://karpathy.github.io/"
  - "https://lilianweng.github.io/"
  - "https://eugeneyan.com/writing/"
  - "https://huyenchip.com/blog/"
  - "https://news.smol.ai/"
  - "https://thezvi.substack.com/"
  - "https://www.dwarkesh.com/s/blog"
  - "https://cognition.ai/blog/1"
  - "https://boristane.com/blog"
  - "https://simonwillison.net/"
  - "https://openai.com/news/"
  - "https://deepmind.google/blog/"
  - "https://www.anthropic.com/engineering"
  - "https://metr.org/research/"
  - "https://codepointerko.substack.com/"
  - "https://lucumr.pocoo.org/"
  - "https://gwern.net/blog/index"
  - "https://www.interconnects.ai/"
  - "https://www.oneusefulthing.org/"
  - "https://www.julian.ac/"
  - "https://www.lesswrong.com/allPosts"

crawler:
  content_limits:
    blog: 3000
    paper: 2000
    readme: 2000

analyzer:
  openai_model: "gpt-4o-mini"
  openai_max_tokens: 1024
  batch_size: 10

delivery:
  discord_max_message_chars: 2000
  discord_max_embed_chars: 4096
